---
- name: Playbook to configure IPA server
  hosts: ipaserver
  become: true

  tasks:
  - name: Get ethernet interface names to be used later for disabling ipv6
    shell: "set -o pipefail && nmcli connection show | grep ethernet | awk '{print $1}'"
    changed_when: false
    register: ethernet_interface_name

  - name:  Disable IPv6 in Network Manager for the main ethernet device
    community.general.nmcli:
      type: ethernet
      conn_name: "{{ item }}"
      method6: disabled
      state: present
    #notify:
    #  - Restart network
    #  - Restart NetworkManager
    with_items: "{{ ethernet_interface_name.stdout_lines }}"

- name: Playbook to install IPA server
  hosts: ipaserver
  become: true

  roles:
  - role: ipaserver
    state: present

- name: Set Up DNS
  ansible.builtin.import_playbook: create_dns_a_record.yml