---

- name: Include a play for IPA cleanup
  vars:
    vm_name: "tang,ipa1,vault,logger,foreman,mirror-reg"
  ansible.builtin.import_playbook: ipa_kvm_clean.yml
  ignore_errors: true

- name: Remove VM Lab
  hosts: localhost
  gather_facts: true
  become: false
  vars:
    vm_name: "tang,ipa1,vault,logger,foreman,mirror-reg"
    libvirt_pool_dir: "/srv/vmdisks"
  tasks:
    - name: Attempt to stop and remove KVM
      block:
        - name: Stop KVM
          community.libvirt.virt:
            name: "{{ item }}"
            command: destroy
          loop:
            "{{ vm_name | split(',') }}"
          failed_when: false
        - name: Remove KVM
          community.libvirt.virt:
            name: "{{ item }}"
            command: undefine
          loop:
            "{{ vm_name | split(',') }}"
          failed_when: false

      always:
        - name: Scrub individual ssh-keys from personal known_hosts file
          lineinfile:
            dest: ~/.ssh/known_hosts
            regexp: '^{{ item }} '
            state: absent
          loop:
            "{{ vm_name | split(',') }}"
        - name: Delete iso from disk
          become: true
          file:
            path: "{{ libvirt_pool_dir }}/{{ item }}/firstboot.iso"
            state: absent
          loop:
            "{{ vm_name | split(',') }}"
        - name: Delete vm from disk
          become: true
          file:
            path: "{{ libvirt_pool_dir }}/{{ item }}/disk01.qcow2"
            state: absent
          loop:
            "{{ vm_name | split(',') }}"
        - name: Delete KVM-specific folder from libvirt
          become: true
          file:
            path: "{{ libvirt_pool_dir }}/{{ item }}"
            state: absent
          loop:
            "{{ vm_name | split(',') }}"
        - name: Undefine vm
          community.libvirt.virt:
            name: "{{ item }}"
            command: undefine
            force: true
          loop:
            "{{ vm_name | split(',') }}"

