- name: Remove VM Lab
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    vm_name: 
      - foo
      - ipa1
    libvirt_pool_dir: "/home/yo_sup/VM"
  tasks:
    - name: Attempt to stop and remove KVM
      block:
        - name: Stop KVM
          community.libvirt.virt:
            name: "{{ item }}"
            command: destroy
          loop:
            "{{ vm_name }}"
        
        - name: Remove KVM
          community.libvirt.virt:
            name: "{{ item }}"
            command: undefine
          loop:
            "{{ vm_name }}"
      always:
        - name: Delete vm from disk
          file:
            path:  "{{ libvirt_pool_dir }}/{{ item }}.qcow2"
            state: absent
          loop:
            "{{ vm_name }}"
    
