- name: Deploys VM based on cloud image
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    vcpus: 2
    ram_mb: 2048
    net: br0

  tasks:
    - name: KVM Provision role
      include_role:
        name: kvm_provision
      vars:
        vm_name: "{{ item }}"
        vm_vcpus: "{{ vcpus }}"
        vm_ram_mb: "{{ ram_mb }}"
        vm_net: "{{ net }}"
        cleanup_tmp: "{{ cleanup }}"
      with_items:
        #- tang
        #- ipa1
        - gitlab
