---
- name: Configure firewalld or syslog server
  hosts: logger_host
  become: true
  tasks:
    - name: Allow incoming syslog traffic to the local host
      ansible.builtin.include_role:
        name: rhel-system-roles.firewall
      vars:
        firewall:
          - port: 514/tcp
            service: syslog
            state: enabled
            runtime: true
            permanent: true

- name: Configure syslog server to receive remote log messages and store them locally
  hosts: logger_host
  become: true
  roles:
    - rhel-system-roles.logging
  vars:
    #logging_certificates:
    #  - name: logging_cert
    #    dns: 'logger.ape.test'
    #    principal: HTTP/logger.ape.test@APE.TEST
    #    ca: ipa
    #logging_pki_files:
    #  - ca_cert: /etc/pki/tls/certs/ca-bundle.crt
    #    cert: /etc/pki/tls/certs/logging_cert.crt
    #    private_key: /etc/pki/tls/private/logging_cert.key
    logging_inputs:
      - name: input_name
        type: remote
        tcp_port: 514
        #tls: true
        #pki_authmode: anon
        #permitted_clients: ['*.ape.test']
    logging_outputs:
      - name: output_name
        type: remote_files
        remote_log_path: /var/log/remote/%FROMHOST%/%PROGRAMNAME:::secpath-replace%.log
        async_writing: true
        client_count: 20
        io_buffer_size: 8192
    logging_flows:
      - name: flow_name
        inputs: [input_name]
        outputs: [output_name]

# Client Configuration
- name: Configure syslog client to send to logger server
  hosts: logger_client
  become: true
  roles:
    - rhel-system-roles.logging
  vars:
    #logging_certificates:
    #  - name: client_cert
    #    dns: 'vault.ape.test'
    #    principal: HTTP/vault.ape.test@APE.TEST
    #    ca: ipa
    #logging_pki_files:
    #  - ca_cert: /etc/pki/tls/certs/ca-bundle.crt
    #    cert: /etc/pki/tls/certs/client_cert.crt
    #    private_key: /etc/pki/tls/private/client_key.key
    logging_inputs:
      - name: basic_input
        type: basics
        use_imuxsock: true
    logging_outputs:
      - name: output_name
        type: forwards
        severity: info
        target: logger.ape.test
        tcp_port: 514
        #tls: true
        #pki_authmode: anon
        #permitted_server: 'logger.ape.test'
    logging_flows:
      - name: flow_name
        inputs: [basic_input]
        outputs: [output_name]
