# ansible-playbook -i localhost, --ask-pass --ask-become-pass ./mgmt.yml -u ape-admin -vvvv
---

- name: Configure APE management node
  hosts: localhost
  become: true
  tasks:

    - name: Install required OS packages
      ansible.builtin.package:
        name:
          - ansible-core
          # - ansible-collection-redhat-rhel_mgmt
          - bind-utils
          - git
          - net-tools
        state: present

    - name: Create various folder under /srv/
      ansible.builtin.file:
        path: /srv/{{ item }}
        state: directory
        owner: root
        #group: libvirt
        group: root
        mode: '2777'
      loop:
        - content_view
        - iso
        - keys
        - software
        - vmdisks 
