# ansible-playbook -i localhost, --ask-pass --ask-become-pass ./mgmt.yml -u ape-admin -vvvv
---

- name: Configure APE management node
  hosts: localhost
  become: true
  vars:
    nmcli_ethernet:
      - conn_name: br0
        int_name: ens15f0
        ip4: '10.40.49.191/24'
        gw4: '10.40.49.1'
        dns:
          - '10.40.49.21'
          - '10.40.49.22'

  tasks:

    - name: Include EPEL repository
      ansible.builtin.yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/
        gpgcheck: no

    - name: Install required OS packages
      ansible.builtin.package:
        name:
          - ansible-core
          # - ansible-collection-redhat-rhel_mgmt
          - bash-completion
          - bind-utils
          - cockpit
          - cockpit-machines
          - cockpit-podman
          - git
          - libvirt
          - net-tools
          - podman
          # - spellcheck   ## Source TBD
          - vim
          - yamllint
        state: present

    - name: Create various folder under /srv/
      ansible.builtin.file:
        path: /srv/{{ item }}
        state: directory
        owner: root
        #group: libvirt
        group: root
        mode: '2777'
      loop:
        - content_view
        - iso
        - keys
        - software
        - vmdisks 

    - name: Introduce bridge network configuration
      block:

        - name: Add bridge connection
          community.general.nmcli:
            type: ethernet
            conn_name: '{{ item.conn_name }}'
            ifname: '{{ item.conn_name }}'
            ip4: '{{ item.ip4 }}'
            gw4: '{{ item.gw4 }}'
            dns4: '{{ item.dns }}'
            state: present
          with_items:
            - '{{ nmcli_ethernet }}'

        - name: Create bridge-slave
          community.general.nmcli:
            type: bridge-slave
            conn_name: '{{ item.int_name }}'
            ifname: '{{ item.int_name }}'
            master: '{{ item.conn_name }}'
            state: present
          with_items:
            - '{{ nmcli_ethernet }}'
