# ansible-playbook -i localhost, --ask-pass --ask-become-pass ./mgmt-ntwk.yml -u ape-admin -vvvv
---

- name: Introduce bridge network configuration
  hosts: localhost
  become: true
  vars:
    nmcli_eth_triad:
      - conn_name: br0
        int_name: ens15f0
        ip4: '10.40.49.199/24'
        gw4: '10.40.49.1'
        dns:
          - '10.40.49.21'
          - '10.40.49.22'
    nmcli_eth_ape:
      - conn_name: br1
        int_name: ens1f0np0
        ip4: '192.168.100.1/24'
        gw4: '10.40.49.1'
        dns:
          - '10.40.49.21'
          - '10.40.49.22'

  tasks:

    # -- TRIAD ---------------------------------------------

    # Maybe NOT delete the interface
    - name: Delete interface 
      community.general.nmcli:
        conn_name: '{{ item.int_name }}'
        state: absent
      with_items:
        - '{{ nmcli_eth_triad }}'
      tags: br0
      when: false

    - name: Delete bridge (br0) connection
      community.general.nmcli:
        conn_name: '{{ item.conn_name }}'
        state: absent
      with_items:
        - '{{ nmcli_eth_triad }}'
      tags: br0

    - name: Add bridge connection
      community.general.nmcli:
        type: ethernet
        conn_name: '{{ item.conn_name }}'
        ifname: '{{ item.conn_name }}'
        ip4: '{{ item.ip4 }}'
        gw4: '{{ item.gw4 }}'
        dns4: '{{ item.dns }}'
        state: present
      with_items:
        - '{{ nmcli_eth_triad }}'
      tags: br0

    - name: Create interface
      community.general.nmcli:
        type: bridge-slave
        conn_name: '{{ item.int_name }}'
        ifname: '{{ item.int_name }}'
        master: '{{ item.conn_name }}'
        state: present
      with_items:
        - '{{ nmcli_eth_triad }}'
      tags: br0

    # -- APE -----------------------------------------------

    # Maybe NOT delete the interface
    - name: Delete interface 
      community.general.nmcli:
        conn_name: '{{ item.int_name }}'
        state: absent
      with_items:
        - '{{ nmcli_eth_ape }}'
      tags: br1
      when: false

    - name: Delete bridge (br0) connection
      community.general.nmcli:
        conn_name: '{{ item.conn_name }}'
        state: absent
      with_items:
        - '{{ nmcli_eth_ape }}'
      tags: br1
      when: false

    - name: Add bridge connection
      community.general.nmcli:
        type: ethernet
        conn_name: '{{ item.conn_name }}'
        ifname: '{{ item.conn_name }}'
        ip4: '{{ item.ip4 }}'
        gw4: '{{ item.gw4 }}'
        dns4: '{{ item.dns }}'
        state: present
      with_items:
        - '{{ nmcli_eth_ape }}'
      tags: br1
      when: false

    - name: Create interface
      community.general.nmcli:
        type: bridge-slave
        conn_name: '{{ item.int_name }}'
        ifname: '{{ item.int_name }}'
        master: '{{ item.conn_name }}'
        state: present
      with_items:
        - '{{ nmcli_eth_ape }}'
      tags: br1
      when: false

  tags: ntwk_cfg
