- name: Open firewall for Tang
  hosts: nbde_servers
  roles:
    - fedora.linux_system_roles.firewall

- name: Deploy NBDE Tang server
  hosts: nbde_servers
  roles:
    - fedora.linux_system_roles.nbde_server

- name: Deploy NBDE Clevis clients
  hosts: nbde_clients
  roles:
    - fedora.linux_system_roles.nbde_client
