- name: Open firewall for Tang
  hosts: nbde_servers
  roles:
    - rhel-system-roles.firewall

- name: Deploy NBDE Tang server
  hosts: nbde_servers
  roles:
    - rhel-system-roles.nbde_server

- name: Deploy NBDE Clevis clients
  hosts: nbde_clients
  roles:
    - rhel-system-roles.nbde_client
