---

- name: Generate certificates for use with Hashicorp Vault
  hosts: vault_host
  become: true
  roles:
    - rhel-system-roles.certificate
  vars:
    certificate_requests:
      - name: "{{ inventory_hostname }}"
        dns: "{{ inventory_hostname }}.{{ dns_name }}"
        principal: "HTTP/{{ inventory_hostname }}.{{ dns_name }}@{{ dns_name | upper }}"
        ca: ipa

- name: Configure firewall, folders, config files, etc. for Hashicorp Vault
  hosts: vault_host
  become: true
  tasks:
    - name: Allow incoming traffic to the local host
      ansible.builtin.include_role:
        name: rhel-system-roles.firewall
      vars:
        firewall:
          - {zone: public, port: [ '8200/tcp', '8201/tcp' ], state: enabled}
    - name: Install podman
      ansible.builtin.package:
        name: podman
        state: present
    - name: Create/update vault user
      ansible.builtin.user:
        name: vault
        comment: 'Hashicorp Vault - Created via ansible'
        uid: 1010
        shell: /bin/bash
        state: present
    - name: Update 'linger' for vault user
      ansible.builtin.shell:
        loginctl enable-linger 1010
    - name: Create target vault configuration files
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        # owner: vault
        # group: vault
        mode: '0755'
      with_items:
        - /opt/vault
        - /opt/vault/logs
        - /opt/vault/file
        - /opt/vault/config
        - /opt/vault/tls
        # - /opt/vault/raft
        # - /opt/vault/raft/data
    - name: Copy CA cert file to vault/tls folder
      ansible.builtin.copy:
        src: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
        dest: /opt/vault/tls/vault-ca.pem
        # owner: vault
        # group: vault
        mode: '0644'
        remote_src: yes
    - name: Copy server cert to vault/tls folder
      ansible.builtin.copy:
        src: /etc/pki/tls/certs/{{ inventory_hostname }}.crt
        dest: /opt/vault/tls/vault-cert.pem
        # owner: vault
        # group: vault
        mode: '0644'
        remote_src: yes
    - name: Copy server private key to vault/tls folder
      ansible.builtin.copy:
        src: /etc/pki/tls/private/{{ inventory_hostname }}.key
        dest: /opt/vault/tls/vault-key.pem
        # owner: vault
        # group: vault
        mode: '0640'
        remote_src: yes
    - name: Copy vault configuration file
      ansible.builtin.template: 
        src: vault.hcl.j2
        dest: /opt/vault/config/config.hcl
        # owner: vault
        # group: vault
        mode: 0640
    - name: Create target folder for software upload
      ansible.builtin.file:
        path: /srv/vault_install
        state: directory
        owner: vault
        mode: '0755'
    - name: Stage 'hc_vault' archive on target for later use
      ansible.builtin.copy:
        src: /srv/software/hc_vault.tar
        dest: /srv/vault_install
        owner: vault
        group: vault
        mode: '0644'

- name: Configure systemd service for Hashicorp Vault container
  hosts: vault_host
  become: true
  tasks:
    - name: Load 'vault' container from source file locally
      containers.podman.podman_load:
        input: /srv/vault_install/hc_vault.tar
    - name: Force systemd to re-read configs
      ansible.builtin.systemd_service:
        daemon_reload: true
    - name: Stage systemd service file for container
      ansible.builtin.template:
        src: vault-pod.service.j2
        dest: /etc/systemd/system/vault-pod.service
        mode: 0644
      register: svc_cfg_file
    - name: Set state of vault container service
      ansible.builtin.systemd_service:
        name: vault-pod
        state: started
        enabled: true
      register: svc_cfg_stat
    - name: If svc changed, force systemd to restart
      ansible.builtin.systemd_service:
        daemon_reexec: true
      when: svc_cfg_file is changed or svc_cfg_stat is changed
