---
# defaults file for kvm_provision
<<<<<<< HEAD
base_image_name: rocky9-template.img 
=======
base_image_name: rocky9-template.img
>>>>>>> main
libvirt_pool_dir: "/srv/vmdisks"
vm_name: rhel9.3-dev
vm_vcpus: 4
vm_ram_mb: 2048
vm_net: br0 
vm_root_pass: toor
<<<<<<< HEAD
ssh_key: /srv/keys/vm_key
=======
ssh_key: "{{ lookup('env', 'HOME') }}/.ssh/personal.pub"
>>>>>>> main

