---
# defaults file for kvm_provision
base_image_name: rocky9-template.qcow2
libvirt_pool_dir: "/srv/vmdisks"
vm_name: rhel9.3-dev
vm_vcpus: 4
vm_ram_mb: 2048
vm_net: br0
vm_mac: 54:42:00:00:ff:ff
vm_root_pass: toor
ansible_user_ssh_key: "/srv/keys/vm_key.pub"
