---
# defaults file for kvm_provision
base_image_name: rhel-8.5-x86_64-kvm.qcow2
libvirt_pool_dir: "/home/yo_sup/VM"
vm_name: rhel8.5-dev
vm_vcpus: 2
vm_ram_mb: 2048
vm_net: host-bridge 
vm_root_pass: toor
ssh_key: /home/yo_sup/.ssh/personal.pub

